spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/glamping
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform : org.hibernate.dialect.PostgreSQLDialect

